CODESEG SEGMENT
    ASSUME CS: CODESEG
    PUBLIC DISPLAY_NUMBER, DISPLAY_TAB, DISPLAY_NEWLINE
    EXTRN DIVIDE_DOUBLEWORD: NEAR  ; 添加此声明

DISPLAY_NUMBER PROC NEAR
    PUSH CX
    PUSH BX
    PUSH SI
    PUSH DI
    MOV DI, 10
    MOV SI, 0

NUMBER_CONVERSION_LOOP:
    MOV CX, 10
    CALL DIVIDE_DOUBLEWORD  ; 调用外部定义的除法子程序
    PUSH CX
    INC SI
    CMP AX, 0
    JNZ NUMBER_CONVERSION_LOOP
    CMP DX, 0
    JNZ NUMBER_CONVERSION_LOOP
    MOV BX, DI
    SUB BX, SI

DISPLAY_DIGITS_LOOP:
    POP DX
    ADD DL, '0'
    MOV AH, 02H
    INT 21H
    DEC SI
    JNZ DISPLAY_DIGITS_LOOP

DISPLAY_SPACES_LOOP:
    CMP BX, 0
    JLE DISPLAY_DONE
    MOV DL, ' '
    MOV AH, 02H
    INT 21H
    DEC BX
    JMP DISPLAY_SPACES_LOOP

DISPLAY_DONE:
    POP DI
    POP SI
    POP BX
    POP CX
    RET
DISPLAY_NUMBER ENDP

DISPLAY_TAB PROC NEAR
    PUSH DX
    PUSH AX
    MOV DL, ' '
    MOV AH, 02H
    INT 21H
    INT 21H
    INT 21H
    INT 21H
    POP AX
    POP DX
    RET
DISPLAY_TAB ENDP

DISPLAY_NEWLINE PROC NEAR
    PUSH DX
    PUSH AX
    MOV DL, 13
    MOV AH, 02H
    INT 21H
    MOV DL, 10
    MOV AH, 02H
    INT 21H
    POP AX
    POP DX
    RET
DISPLAY_NEWLINE ENDP

CODESEG ENDS

END
